
title: "Felipe Galindo (@Felipegalind0)"
author: "Felipe Galindo"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"



permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
google_analytics: UA-252839005-1

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
#  - {url: "/Felipegalind0_resume.pdf", title: CV}
  - {url: "http://UMN-VR.github.io", title: UMN-VR}
  - {url: "https://github.com/sponsors/Felipegalind0", title: Sponsor Me 😊}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mailto:felipegalind0@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/Felipegalind0"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Felipegalind0"}
  - {title: Facebook, icon: facebook, url: "https://facebook.com/Felipegalind0"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/Felipegalind0"}
  - {title: BeReal, url: "https://bere.al/felipegalind0"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/felipegalind0/"}
  - {title: YouTube, icon: youtube, url: "https://www.youtube.com/@Felipegalind0"}
  - {title: VSCO, url: "https://vsco.co/felipegalind0"}
  - {title: Source Code, url: "https://github.com/Felipegalind0/Felipegalind0.github.io"} 

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
