title: "Felipe Galindo (@Felipegalind0)"
author: "Felipe Galindo"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/Felipegalind0_resume.pdf", title: "CV", icon: home"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:felipegalind0@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/Felipegalind0"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/KathrynSchuler"}

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
 - jekyll-remote-theme
 - jekyll-feed
